const path = require('path');

const APP_CONSTANTS = {
  DEFAULT_PORT: 3333,
  DEFAULT_BRAIN_MODEL: 'gpt-5-mini',
  DEFAULT_COPILOT_API_URL: 'http://localhost:4141',
  DEFAULT_OPENROUTER_REFERER: 'http://localhost:3333',
  JSON_BODY_LIMIT: '10mb',
  DEFAULT_MEMORY_API_LIMIT: 100,
  DEFAULT_LOGS_API_LIMIT: 200,
  DEFAULT_WS_HISTORY_LIMIT: 30,
  LOG_PREVIEW_LENGTH: 80,
};

const PATH_CONSTANTS = {
  BACKEND_ROOT: path.join(__dirname, '..'),
  FRONTEND_DIST_DIR: path.join(__dirname, '..', '..', 'frontend', 'dist'),
};

const MEMORY_CONSTANTS = {
  MAX_HISTORY: 500,
  CHARS_PER_TOKEN: 4,
  DEFAULT_TOKEN_BUDGET: 3000,
  DEFAULT_HISTORY_LIMIT: 100,
  ALWAYS_INCLUDE_LAST_N: 6,
  PROMPT_OVERHEAD_CHARS: 200,
  MESSAGE_OVERHEAD_CHARS: 30,
  CONTEXT_MESSAGE_HARD_CAP: 40,
  KEYWORD_MIN_LENGTH: 2,
  KEYWORD_STATS_LIMIT: 8,
};

const BRAIN_CONSTANTS = {
  MODEL_DISCOVERY_TIMEOUT_MS: 3000,
  STREAM_MAX_TOKENS: 4096,
  CALL_MAX_TOKENS: 2048,
  TOKEN_BUDGET: 4000,
  TOOL_LOOP_LIMIT: 20,
  SUMMARY_MIN_HISTORY: 10,
  SUMMARY_HISTORY_LIMIT: 50,
};

const AGENT_CONSTANTS = {
  API_KEY_MIN_LENGTH: 8,
  CONTEXT_NOTES_MAX_LENGTH: 2000,
  CONTEXT_NOTE_SUMMARY_LENGTH: 300,
  TOKEN_BUDGET: 3000,
  PROVIDER_MAX_TOKENS: 4096,
  OPENROUTER_AUTO_MODEL_THRESHOLD: 8000,
  AUTO_UPDATE_MIN_RESPONSE_LENGTH: 50,
  AUTO_UPDATE_QUESTION_PREVIEW_LENGTH: 100,
  AUTO_UPDATE_ANSWER_PREVIEW_LENGTH: 200,
};

const TELEGRAM_CONSTANTS = {
  MESSAGE_LOG_LIMIT: 100,
  MESSAGE_CHUNK_SIZE: 4000,
  MESSAGE_PREVIEW_LENGTH: 200,
  LOG_PREVIEW_LENGTH: 80,
  AUTORECONNECT_DELAY_MS: 3000,
  POLLING_CONFLICT_CODE: '409',
};

const LOGGER_CONSTANTS = {
  MAX_LOGS: 1000,
  DEFAULT_LOG_LIMIT: 200,
  RANDOM_ID_SUFFIX_LENGTH: 4,
};

const SELF_LEARN_CONSTANTS = {
  MAX_LESSONS: 200,
  TOOL_TIMEOUT_SECONDS: 60,
  TOOL_ARGS_PREVIEW_LENGTH: 50,
  ERROR_PREVIEW_LENGTH: 100,
  LESSON_PREVIEW_LENGTH: 100,
  PREVIOUS_INPUT_PREVIEW_LENGTH: 80,
  PREVIOUS_RESPONSE_PREVIEW_LENGTH: 80,
  LESSON_LOG_PREVIEW_LENGTH: 80,
  USER_CORRECTION_PREVIEW_LENGTH: 120,
  ROUTING_KEYWORD_MIN_LENGTH: 3,
  ROUTING_KEYWORD_LIMIT: 5,
  RELEVANT_LESSON_LIMIT: 3,
};

const TOOL_CONSTANTS = {
  COMMAND_TIMEOUT_MS: 15000,
  COMMAND_MAX_BUFFER_BYTES: 1024 * 1024,
  COMMAND_OUTPUT_PREVIEW_LENGTH: 3000,
  ERROR_OUTPUT_PREVIEW_LENGTH: 500,
  PIPELINE_STEP_TIMEOUT_MS: 60000,
  FILE_MAX_SIZE_BYTES: 512 * 1024,
  FILE_CONTENT_PREVIEW_LENGTH: 8000,
  HTTP_DEFAULT_TIMEOUT_MS: 10000,
  HTTP_TEXT_PREVIEW_LENGTH: 10000,
  SEARCH_DEFAULT_RESULTS: 5,
  SEARCH_MAX_RESULTS: 10,
  SEARCH_TITLE_PREVIEW_LENGTH: 100,
  SEARCH_SNIPPET_PREVIEW_LENGTH: 300,
  TOOL_LOG_ARGS_PREVIEW_LENGTH: 100,
  TOOL_LOG_RESULT_PREVIEW_LENGTH: 200,
  TELEGRAM_PREVIEW_LENGTH: 100,
};

module.exports = {
  APP_CONSTANTS,
  PATH_CONSTANTS,
  MEMORY_CONSTANTS,
  BRAIN_CONSTANTS,
  AGENT_CONSTANTS,
  TELEGRAM_CONSTANTS,
  LOGGER_CONSTANTS,
  SELF_LEARN_CONSTANTS,
  TOOL_CONSTANTS,
};