/**
 * self-learn.js — Self-improvement engine (v2)
 *
 * Improvements over v1:
 *   - Structured lesson format: priority, status, area, recurrenceCount, tags
 *   - Recurrence tracking: same trigger → increments count instead of duplicate
 *   - Promotion engine: recurrenceCount >= 3 → auto-promote to BRAIN_SYSTEM
 *   - Workspace files: writes LEARNINGS.md, ERRORS.md, FEATURE_REQUESTS.md
 *   - Feature request detection: "có thể", "nếu có", "thêm tính năng", "wish"...
 *   - Promoted lessons injected into brain system prompt at runtime
 *
 * Storage:
 *   - Supabase `lessons` table (runtime, queryable)
 *   - backend/workspace/LEARNINGS.md      (human-readable, inspectable)
 *   - backend/workspace/ERRORS.md         (tool/API failures)
 *   - backend/workspace/FEATURE_REQUESTS.md (user wishes)
 */

const fs = require('fs');
const path = require('path');
const db = require('./db');
const logger = require('./logger');
const memory = require('./memory');
const { SELF_LEARN_CONSTANTS, PATH_CONSTANTS } = require('./constants');

// ─── Types ────────────────────────────────────────────────────────────────────

/**
 * Lesson entry structure (v2)
 * @typedef {Object} Lesson
 * @property {string}   id
 * @property {string}   type         - tool_error | user_correction | pattern | routing | fact | feature_request | knowledge_gap | best_practice
 * @property {string}   priority     - low | medium | high | critical
 * @property {string}   status       - pending | promoted | resolved | wont_fix
 * @property {string}   area         - routing | tool | memory | api | ui | content | config | unknown
 * @property {string}   trigger      - short key (≤60 chars)
 * @property {string}   lesson       - the actual lesson text
 * @property {string[]} tags         - searchable tags
 * @property {number}   recurrenceCount
 * @property {number}   firstSeen
 * @property {number}   lastSeen
 * @property {string}   [context]    - optional extra context
 */

let lessons = [];
let promotedLessons = []; // lessons with recurrenceCount >= PROMOTE_THRESHOLD

const PROMOTE_THRESHOLD = 3;
const WORKSPACE_DIR = path.join(PATH_CONSTANTS.BACKEND_ROOT, 'workspace');

// ─── Workspace file helpers ───────────────────────────────────────────────────

function ensureWorkspaceDir() {
  if (!fs.existsSync(WORKSPACE_DIR)) {
    fs.mkdirSync(WORKSPACE_DIR, { recursive: true });
  }
}

function workspacePath(filename) {
  return path.join(WORKSPACE_DIR, filename);
}

function appendToWorkspaceFile(filename, entry) {
  ensureWorkspaceDir();
  const filepath = workspacePath(filename);
  const timestamp = new Date().toLocaleString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' });
  const line = `\n---\n**[${timestamp}]** \`${entry.priority.toUpperCase()}\` · \`${entry.area}\`\n\n${entry.lesson}\n\n*Tags: ${entry.tags.join(', ')}*\n`;
  fs.appendFileSync(filepath, line, 'utf8');
}

function initWorkspaceFile(filename, header) {
  ensureWorkspaceDir();
  const filepath = workspacePath(filename);
  if (!fs.existsSync(filepath)) {
    fs.writeFileSync(filepath, `# ${header}\n> Auto-generated by Brain OS self-learn engine\n`, 'utf8');
  }
}

function rewriteWorkspaceFile(filename, header, entries) {
  ensureWorkspaceDir();
  const lines = [`# ${header}\n> Auto-generated by Brain OS self-learn engine\n`];
  for (const e of entries) {
    const ts = new Date(e.lastSeen).toLocaleString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' });
    lines.push(
      `\n---\n**[${ts}]** \`${e.priority.toUpperCase()}\` · \`${e.area}\`  ` +
      `· recurrence: **${e.recurrenceCount}** · status: \`${e.status}\`\n\n` +
      `${e.lesson}\n\n*Tags: ${e.tags.join(', ')}*\n`
    );
  }
  fs.writeFileSync(workspacePath(filename), lines.join(''), 'utf8');
}

// ─── Persistence ──────────────────────────────────────────────────────────────

async function loadLessons() {
  const { data, error } = await db.from('lessons').select('*').order('created_at');
  if (error) throw new Error(`[self-learn] Load failed: ${error.message}`);
  lessons = data ? data.map(r => ({ ...r.data, id: r.id })) : [];

  // Migrate v1 lessons (missing new fields) to v2 format
  lessons = lessons.map(l => ({
    priority: 'medium',
    status: 'pending',
    area: inferArea(l.type, l.lesson || ''),
    tags: inferTags(l.type, l.trigger || '', l.lesson || ''),
    recurrenceCount: l.recurrenceCount || 1,
    firstSeen: l.firstSeen || l.timestamp || Date.now(),
    lastSeen: l.lastSeen || l.timestamp || Date.now(),
    context: '',
    ...l,
  }));

  // Rebuild promoted list
  promotedLessons = lessons.filter(l => l.recurrenceCount >= PROMOTE_THRESHOLD && l.status !== 'wont_fix');

  // Init workspace files
  initWorkspaceFile('LEARNINGS.md', 'Brain OS — Learnings');
  initWorkspaceFile('ERRORS.md', 'Brain OS — Tool & API Errors');
  initWorkspaceFile('FEATURE_REQUESTS.md', 'Brain OS — Feature Requests');

  logger.info('self-learn', `Loaded ${lessons.length} lessons (${promotedLessons.length} promoted)`);
}

function saveLessons() {
  const rows = lessons.map(l => ({
    id: l.id || Date.now().toString(36),
    data: l,
    created_at: new Date(l.firstSeen || Date.now()).toISOString(),
  }));
  db.from('lessons').upsert(rows).then(({ error }) => {
    if (error) logger.warn('self-learn', `Persist failed: ${error.message}`);
  });
}

function clearLessons() {
  lessons = [];
  promotedLessons = [];
  db.from('lessons').delete().neq('id', '').catch(() => {});
  // Clear workspace files
  ['LEARNINGS.md', 'ERRORS.md', 'FEATURE_REQUESTS.md'].forEach(f => {
    const fp = workspacePath(f);
    if (fs.existsSync(fp)) fs.unlinkSync(fp);
  });
}

// ─── Inference helpers ────────────────────────────────────────────────────────

function inferArea(type, text) {
  if (type === 'tool_error') return 'tool';
  if (type === 'user_correction') return 'routing';
  if (type === 'feature_request') return 'ui';
  if (/agent|call_agent|route/i.test(text)) return 'routing';
  if (/api|http|fetch|request/i.test(text)) return 'api';
  if (/memory|context|summary/i.test(text)) return 'memory';
  if (/config|env|key|token/i.test(text)) return 'config';
  return 'unknown';
}

function inferPriority(type, recurrenceCount = 1) {
  if (type === 'tool_error' || type === 'user_correction') {
    if (recurrenceCount >= PROMOTE_THRESHOLD) return 'high';
    return 'medium';
  }
  if (type === 'feature_request') return 'low';
  if (type === 'best_practice') return 'medium';
  return 'low';
}

function inferTags(type, trigger, lesson) {
  const tags = [type];
  const combined = `${trigger} ${lesson}`.toLowerCase();
  if (/search|web|duckduckgo|brave|tavily/i.test(combined)) tags.push('search');
  if (/agent|call_agent|pipeline/i.test(combined)) tags.push('agents');
  if (/tool|function|error/i.test(combined)) tags.push('tools');
  if (/memory|context|history/i.test(combined)) tags.push('memory');
  if (/telegram/i.test(combined)) tags.push('telegram');
  if (/file|read|write/i.test(combined)) tags.push('files');
  return [...new Set(tags)];
}

// ─── Promotion engine ─────────────────────────────────────────────────────────

/**
 * Check if a lesson should be promoted and update its status.
 * Promoted lessons get injected into BRAIN_SYSTEM context.
 */
function maybePromote(lesson) {
  if (lesson.status === 'wont_fix' || lesson.status === 'resolved') return;
  if (lesson.recurrenceCount >= PROMOTE_THRESHOLD && lesson.status !== 'promoted') {
    lesson.status = 'promoted';
    lesson.priority = lesson.priority === 'low' ? 'medium' : lesson.priority;

    if (!promotedLessons.find(p => p.id === lesson.id)) {
      promotedLessons.push(lesson);
    }

    logger.info('self-learn',
      `🎯 Promoted lesson (recurrence=${lesson.recurrenceCount}): ${lesson.lesson.slice(0, 80)}`
    );

    // Rewrite workspace files to reflect promotion
    syncWorkspaceFiles();
  }
}

function syncWorkspaceFiles() {
  const byType = (types) => lessons.filter(l => types.includes(l.type))
    .sort((a, b) => b.recurrenceCount - a.recurrenceCount);

  rewriteWorkspaceFile('LEARNINGS.md', 'Brain OS — Learnings',
    byType(['user_correction', 'pattern', 'routing', 'fact', 'best_practice', 'knowledge_gap'])
  );
  rewriteWorkspaceFile('ERRORS.md', 'Brain OS — Tool & API Errors',
    byType(['tool_error'])
  );
  rewriteWorkspaceFile('FEATURE_REQUESTS.md', 'Brain OS — Feature Requests',
    byType(['feature_request'])
  );
}

// ─── Core: storeLesson ────────────────────────────────────────────────────────

function storeLesson({ type, trigger, lesson, context = '', priority, area, tags }) {
  const now = Date.now();

  // Deduplicate by trigger — increment recurrenceCount instead of adding duplicate
  const existing = lessons.find(l => l.trigger === trigger);
  if (existing) {
    existing.recurrenceCount += 1;
    existing.lastSeen = now;
    existing.lesson = lesson; // update with latest version
    if (context) existing.context = context;
    // Re-infer priority based on new recurrence
    existing.priority = inferPriority(existing.type, existing.recurrenceCount);

    saveLessons();
    maybePromote(existing);

    logger.debug('self-learn',
      `Updated lesson (×${existing.recurrenceCount}): ${trigger.slice(0, 60)}`
    );
    return existing;
  }

  // New lesson
  const entry = {
    id: now.toString(36) + Math.random().toString(36).slice(2, 6),
    type,
    priority: priority || inferPriority(type, 1),
    status: 'pending',
    area: area || inferArea(type, lesson),
    trigger: trigger.slice(0, 60),
    lesson,
    tags: tags || inferTags(type, trigger, lesson),
    recurrenceCount: 1,
    firstSeen: now,
    lastSeen: now,
    context,
  };

  lessons.push(entry);
  if (lessons.length > SELF_LEARN_CONSTANTS.MAX_LESSONS) {
    // Remove oldest non-promoted low-priority lessons first
    const idx = lessons.findIndex(l => l.priority === 'low' && l.status !== 'promoted');
    if (idx !== -1) lessons.splice(idx, 1);
    else lessons.shift();
  }

  saveLessons();

  // Inject into memory so Prompt Assembler picks it up this session
  memory.store('system', `[LESSON] ${lesson}`, 'brain', { _lesson: true });

  // Write to workspace file
  const workspaceFile = type === 'tool_error' ? 'ERRORS.md'
    : type === 'feature_request' ? 'FEATURE_REQUESTS.md'
    : 'LEARNINGS.md';
  appendToWorkspaceFile(workspaceFile, entry);

  logger.info('self-learn',
    `New ${type} lesson [${entry.priority}]: ${lesson.slice(0, SELF_LEARN_CONSTANTS.LESSON_LOG_PREVIEW_LENGTH)}`
  );

  return entry;
}

// ─── Specialized store functions ──────────────────────────────────────────────

function learnFromToolError({ toolName, args, error, userInput }) {
  let lesson = '';
  let priority = 'medium';

  if (toolName === 'call_agent' && error?.includes('not found')) {
    lesson = `When calling agent "${args?.agent_id}", it didn't exist. Always call list_agents first to verify agent IDs.`;
    priority = 'high';
  } else if (toolName === 'run_command' && error?.includes('blocked')) {
    lesson = `Command "${args?.command}" is blocked by whitelist. Only read-only commands allowed.`;
  } else if (toolName === 'import_skill' && error?.includes('404')) {
    lesson = `Skill import via slug fails with 404. Use full raw GitHub URL instead: GitHub → file → Raw → copy URL.`;
    priority = 'high';
  } else if (error?.includes('timeout')) {
    lesson = `Tool ${toolName} timed out on: "${(userInput || '').slice(0, 50)}". Consider breaking task into smaller steps.`;
  } else if (toolName === 'search_web' && error?.includes('rate')) {
    lesson = `search_web is rate-limited. Tavily/Brave APIs are more reliable than DuckDuckGo Instant.`;
    priority = 'high';
  } else {
    lesson = `Tool ${toolName} failed: ${(error || '').slice(0, SELF_LEARN_CONSTANTS.ERROR_PREVIEW_LENGTH)}`;
  }

  return storeLesson({
    type: 'tool_error',
    trigger: `${toolName}:${JSON.stringify(args || {}).slice(0, 40)}`,
    lesson,
    priority,
    area: 'tool',
  });
}

function learnFromCorrection({ userCorrection, previousResponse, previousInput }) {
  const lesson = `When asked "${(previousInput || '').slice(0, SELF_LEARN_CONSTANTS.PREVIOUS_INPUT_PREVIEW_LENGTH)}", the response "${(previousResponse || '').slice(0, SELF_LEARN_CONSTANTS.PREVIOUS_RESPONSE_PREVIEW_LENGTH)}" was wrong. User corrected: "${userCorrection.slice(0, SELF_LEARN_CONSTANTS.USER_CORRECTION_PREVIEW_LENGTH)}". Avoid repeating this.`;

  return storeLesson({
    type: 'user_correction',
    trigger: (previousInput || '').slice(0, 60),
    lesson,
    priority: 'high',
    area: 'routing',
  });
}

function learnRoutingPattern({ userInput, agentUsed, successful }) {
  if (!successful) return;
  const keywords = userInput.toLowerCase()
    .split(/\W+/)
    .filter(w => w.length > SELF_LEARN_CONSTANTS.ROUTING_KEYWORD_MIN_LENGTH)
    .slice(0, SELF_LEARN_CONSTANTS.ROUTING_KEYWORD_LIMIT);
  if (!keywords.length) return;

  const lesson = `Pattern: when user asks about "${keywords.join(', ')}", ${agentUsed} handles it well.`;

  return storeLesson({
    type: 'routing',
    trigger: keywords.join('-'),
    lesson,
    area: 'routing',
  });
}

function learnFeatureRequest({ userInput, context = '' }) {
  const lesson = `User wants: "${userInput.slice(0, 200)}". Consider implementing or noting as future capability.`;

  return storeLesson({
    type: 'feature_request',
    trigger: userInput.slice(0, 60),
    lesson,
    priority: 'low',
    area: 'ui',
    context,
  });
}

// ─── Detection patterns ───────────────────────────────────────────────────────

const CORRECTION_PATTERNS = [
  /không phải/i, /sai rồi/i, /ý tôi là/i, /không đúng/i,
  /no,?\s+i mean/i, /that'?s wrong/i, /incorrect/i,
  /thực ra/i, /actually/i, /nhưng mà/i, /you misunderstood/i,
  /hiểu nhầm/i, /không phải vậy/i,
];

const SATISFACTION_PATTERNS = [
  /đúng rồi/i, /chính xác/i, /cảm ơn/i, /tuyệt/i, /ok$/i,
  /perfect/i, /exactly/i, /that'?s right/i, /good job/i,
  /great/i, /thanks/i,
];

const FEATURE_REQUEST_PATTERNS = [
  /có thể thêm/i, /nếu có thể/i, /ước gì/i, /would be nice/i,
  /wish you could/i, /can you add/i, /thêm tính năng/i,
  /feature request/i, /tôi muốn/i, /tôi cần.*nhưng.*không có/i,
];

function detectCorrectionType(userInput) {
  if (CORRECTION_PATTERNS.some(p => p.test(userInput))) return 'correction';
  if (FEATURE_REQUEST_PATTERNS.some(p => p.test(userInput))) return 'feature_request';
  if (SATISFACTION_PATTERNS.some(p => p.test(userInput))) return 'satisfaction';
  return null;
}

// ─── Post-conversation analysis ───────────────────────────────────────────────

async function analyzeConversation({ userInput, brainResponse, toolsUsed, errors }) {
  const type = detectCorrectionType(userInput);

  if (type === 'correction') {
    const hist = memory.getHistory('brain', 10);
    const prevAssistant = [...hist].reverse().find(m => m.role === 'assistant');
    const prevUser = [...hist].reverse().find(m => m.role === 'user' && m.content !== userInput);
    if (prevAssistant) {
      learnFromCorrection({
        userCorrection: userInput,
        previousResponse: prevAssistant.content,
        previousInput: prevUser?.content || '',
      });
    }
  }

  if (type === 'feature_request') {
    learnFeatureRequest({ userInput });
  }

  if (errors?.length) {
    for (const err of errors) {
      if (err.tool) learnFromToolError(err);
    }
  }
}

// ─── Context builders ─────────────────────────────────────────────────────────

/**
 * Get lessons relevant to current user input (for Prompt Assembler).
 */
function getRelevantLessons(userInput, limit = SELF_LEARN_CONSTANTS.RELEVANT_LESSON_LIMIT) {
  const words = new Set(
    userInput.toLowerCase()
      .split(/\W+/)
      .filter(w => w.length > SELF_LEARN_CONSTANTS.ROUTING_KEYWORD_MIN_LENGTH)
  );

  return lessons
    .filter(l => l.status !== 'wont_fix')
    .map(l => {
      const lWords = l.lesson.toLowerCase().split(/\W+/)
        .filter(w => w.length > SELF_LEARN_CONSTANTS.ROUTING_KEYWORD_MIN_LENGTH);
      const overlap = lWords.filter(w => words.has(w)).length;
      // Boost score for promoted/high-priority lessons
      const boost = l.status === 'promoted' ? 2 : l.priority === 'high' ? 1 : 0;
      return { ...l, score: overlap + boost };
    })
    .filter(l => l.score > 0)
    .sort((a, b) => b.score - a.score || b.recurrenceCount - a.recurrenceCount || b.lastSeen - a.lastSeen)
    .slice(0, limit)
    .map(l => l.lesson);
}

/**
 * Build context string injected into system prompt.
 * Promoted lessons appear first, then relevant ones.
 */
function buildLessonsContext(userInput) {
  // Always include promoted lessons (max 5)
  const promoted = promotedLessons
    .filter(l => l.status === 'promoted')
    .slice(0, 5)
    .map(l => `[RULE ×${l.recurrenceCount}] ${l.lesson}`);

  // Then relevant non-promoted lessons
  const relevant = getRelevantLessons(userInput)
    .filter(l => !promoted.some(p => p.includes(l)));

  const all = [...promoted, ...relevant];
  if (!all.length) return '';

  return `\n\n## Learned Rules & Patterns\n${all.map((l, i) => `${i + 1}. ${l}`).join('\n')}`;
}

// ─── Stats ────────────────────────────────────────────────────────────────────

function getStats() {
  const byType = {};
  const byPriority = {};
  const byStatus = {};

  for (const l of lessons) {
    byType[l.type] = (byType[l.type] || 0) + 1;
    byPriority[l.priority] = (byPriority[l.priority] || 0) + 1;
    byStatus[l.status] = (byStatus[l.status] || 0) + 1;
  }

  return {
    total: lessons.length,
    promoted: promotedLessons.length,
    by_type: byType,
    by_priority: byPriority,
    by_status: byStatus,
    workspace_dir: WORKSPACE_DIR,
    workspace_files: ['LEARNINGS.md', 'ERRORS.md', 'FEATURE_REQUESTS.md']
      .map(f => ({ file: f, exists: fs.existsSync(workspacePath(f)) })),
  };
}

// ─── Exports ──────────────────────────────────────────────────────────────────

module.exports = {
  init: loadLessons,
  storeLesson,
  learnFromToolError,
  learnFromCorrection,
  learnRoutingPattern,
  learnFeatureRequest,
  analyzeConversation,
  buildLessonsContext,
  getRelevantLessons,
  getStats,
  clearLessons,
  syncWorkspaceFiles,

  // Getters
  getLessons: () => lessons,
  getLessonCount: () => lessons.length,
  getPromotedLessons: () => promotedLessons,

  // Mark a lesson as resolved or wont_fix
  resolvelesson: (id, status = 'resolved') => {
    const l = lessons.find(x => x.id === id);
    if (!l) return null;
    l.status = status;
    if (status === 'resolved' || status === 'wont_fix') {
      promotedLessons = promotedLessons.filter(p => p.id !== id);
    }
    saveLessons();
    syncWorkspaceFiles();
    return l;
  },
};