export const APP_CONSTANTS = {
  THEME_STORAGE_KEY: 'theme',
  DEFAULT_THEME: 'dark',
  STATUS_REFETCH_INTERVAL_MS: 30_000,
  LOGS_QUERY_LIMIT: 200,
  CHAT_HISTORY_LIMIT: 50,
  MAX_LOG_ENTRIES: 500,
  WS_RECONNECT_DELAY_MS: 2_000,
  CHAT_AVATAR_SIZE: 34,
  STATUS_DOT_SIZE: 7,
  SIDEBAR_STATUS_DOT_SIZE: 6,
}